"use client";
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }
import '../public/css/styles.css';
import {Header} from './Header';
import { StyleProvider, ThemePicker } from 'vcc-ui';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StyleProvider>
      <ThemePicker variant="light">
        <html lang="en">
          <body>
            <Header />
            {children}
          </body>
        </html>
      </ThemePicker>
  </StyleProvider>
    
  )
}
